packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  msw: false

minimumReleaseAgeExclude:
  - "@internationalized/date@3.12.4"
  - "@internationalized/number@3.6.8"
  - "lucide-react@1.39.0"
  - "react-aria-components@1.21.0"
  - "react-aria@3.52.0"
  - "react-stately@3.50.0"

catalog:
  "@types/node": ^24.13.3 # LTS support
  "typescript": ^6.0.3 # Library compatability

catalogs:
  react19:
    "react": "^19.2.8"
    "react-dom": "^19.2.8"
    "@types/react": "^19.2.18"
    "@types/react-dom": "^19.2.5"
