nodeVersion: "24.20.0"

sharedWorkspaceLockfile: true
strictPeerDependencies: true
engineStrict: true
preferOffline: true

# Allow root installation
ignoreWorkspaceRootCheck: true

packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true
  sharp: true
  msw: false

catalog:
  "astro": ^7.3.1
  "@types/node": ^24.13.3 # LTS support
  "typescript": ^6.0.3 # Library compatability
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0

catalogs:
  react19:
    "react": "^19.2.8"
    "react-dom": "^19.2.8"
    "@types/react": "^19.2.18"
    "@types/react-dom": "^19.2.5"

overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - astro@7.3.1
