name: Cache static files on AWS S3 storage

env:
  STATIC_PATH: /public/static/

on:
  push:
    paths:
      - "*/public/static/*"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: build and upload to s3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: copy static directory with s3
        run: aws s3 sync ./public/static/. s3://my-gatsby-contents
